@TaskManagementApp.Api_HostAddress = http://localhost:5156

POST http://localhost:5156/api/auth/register
Content-Type: application/json

{
  "username": "sameed",
  "email": "sameed@test.com",
  "password": "SecurePassword123"
}

###
